version: '3.9'
services:
  api:
    build: ./services/api
    ports: ['4001:4001']
  search:
    build: ./services/search
    ports: ['4002:4002']
    environment:
      SEARCH_PORT: 4002
  mlbridge:
    build: ./services/ml-bridge
    ports: ['8001:8001']
  redis:
    image: redis:7
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: secret
