version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    environment:
      API_JWT_SECRET: ${API_JWT_SECRET:-change_me}
      PORT: 4001
      ML_BRIDGE_URL: http://ml:8001
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://web:3000
    ports:
      - '4001:4001'
    depends_on:
      - ml

  ml:
    build:
      context: .
      dockerfile: services/ml-bridge/Dockerfile
    environment:
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8001
    ports:
      - '8001:8001'

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://api:4001
    ports:
      - '3000:3000'
    depends_on:
      - api
