version: '3.9'

services:
  search-db:
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realestate
    volumes:
      - search-db-data:/var/lib/postgresql/data

volumes:
  search-db-data:
