global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:9101

  - job_name: search
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:9102

  - job_name: ingestion
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:9103
