replicaCount: 2
nameOverride: ""
fullnameOverride: ""
image:
  repository: ghcr.io/herbiea7368/realestate-ai-uae
  tag: v1.0.0
service:
  type: ClusterIP
  port: 4001
resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
envConfigMapName: realestate-ai-env
envSecretName: ""
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
