openapi: 3.1.0
info:
  title: Permit Compliance Service
  version: 0.1.0
servers:
  - url: http://localhost:4000/api/v1
paths:
  /permits/check:
    post:
      summary: Validate a permit for a property
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ../../packages/compliance-contracts/schemas/permit-check-request.schema.json
      responses:
        "200":
          description: Permit validation result
          content:
            application/json:
              schema:
                $ref: ../../packages/compliance-contracts/schemas/permit-status-response.schema.json
  /permits/status:
    get:
      summary: Retrieve permit status by Trakheesi number
      parameters:
        - in: query
          name: trakheesi
          required: true
          schema:
            type: string
            pattern: "^[0-9]{6}$"
      responses:
        "200":
          description: Permit status payload
          content:
            application/json:
              schema:
                $ref: ../../packages/compliance-contracts/schemas/permit-status-response.schema.json

