name: ci

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: realestate
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.18.1
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e services/ml-bridge[dev]
      - name: Lint
        run: pnpm lint
      - name: Test API
        run: pnpm --filter @realestate-ai-uae/api test
      - name: Test Search service
        run: pnpm --filter @realestate-ai-uae/search test
      - name: Test Ingestion service
        run: pnpm --filter @realestate-ai-uae/ingestion test
      - name: Metrics smoke checks
        run: pnpm tsx tools/metrics-smoke.ts
      - name: Test ML bridge
        run: python -m pytest services/ml-bridge/tests
      - name: Typecheck
        run: pnpm typecheck
      - name: Build web app
        run: pnpm --filter @realestate-ai-uae/web build
      - name: Install Playwright browsers
        run: pnpm playwright:install
      - name: Playwright smoke test
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:3000
        run: pnpm test:e2e
      - name: Upload audit log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: audit-log
          path: services/api/logs/audit.log
          if-no-files-found: ignore
      - name: Upload API test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-artifacts
          path: |
            services/api/coverage/**
            services/api/coverage/junit.xml
          if-no-files-found: ignore
      - name: Upload search test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: search-test-artifacts
          path: services/search/junit.xml
          if-no-files-found: ignore
